- >-
    "<b>STEPPED APPLICATION PHASE"
-
    image:
        path: "Assets/Game/Images/SteppedApplicationPhase.png"
        description: "Stepped Application Phase"
        source: "Code_A (2022)"
- >-
    NOTE: CLICK THE IMAGE FOR BETTER GUIDE OF INSTRUCTIONS.

    Is the last phase of the game that is playable in both the professional and non-professional modes of the game where the player is be given seven (7) missions to be completed.
    
    Mechanics Of The Game
        The following are the things to be considered in the stepped application.
        1. There are seven (8) missions on this phase that has to be completed.
        2. Each mission is a prerequisite of the next mission.
        3. Before proceeding to the missions, the player needs to perform the pre-diving check-up which is 10% of the total score.
        4. The player needs to check the BLOWBAGETS: The battery, lights, oil, water, brakes, air, gas, engine, tires, and the self.
        5. At the beginning of each mission, the player must buckle up.
        6. The player must navigate the controls properly for him/her to clear the missions efficiently.
        7. There is one life in every mission.
        8. The player must avoid bumping into other parked vehicles and pedestrians to preserve life.
        9. After completing the mission, the player is going to be redirected to the next mission automatically.
        10. Once the missions are successfully cleared, a display will be seen that the missions are successfully completed.

    CONTROLS and INDICATORS
        Are the interactable interfaces that can be navigated by the player.

        Signal Lights – Signal for turning right or left for safe driving and parking.
        Steering Wheel - Navigation of the vehicle's direction.
        Key - Is required to start and can stop the engine.
        Handbrake - Hand-operated brake.
        1st Gear - The least possibility for speed gain.
        2nd Gear - Increases speed on ordinary roads after 1st gear. 
        3rd Gear - Increases the speed further from 2nd gear. 	
        4th Gear - Increases the speed from 3rd gear. 
        5th Gear - Allows the least pulling power and a great range of speed.
        Reverse Button - Drives the vehicle backwards.
        Neutral Button - Stops the motion of the vehicle.
        Clutch Pedal - Allows the driver to shift gears smoothly. 
        Brake Pedal - Stops the vehicle temporarily.
        Accelerator - Drives the vehicle forward.
        Speedometer - Indicates the speed of the vehicle