- >-
    "<b>STEPPED APPLICATION PHASE"
-
    image:
        path: "Assets/Game/Images/SteppedApplicationPhase.png"
        description: "Stepped Application Phase"
        source: "Code_A (2022)"
- >-
    NOTE: PINDUTIN ANG IMAHEN PARA SA MAS MADALING PAG-INTINDI NG LARO.

        Ang yugto ng larong ito ay maaaring laruin sa parehong Propesyonal at Hindi-Propesyonal na uri kung saan ang manlalaro ay bibigyan ng misyon na kailangan niyang makumpleto. Ang mga misyon ay kailangang gawin ayon sa pagkasunod-sunod nito.
    
    "<b>Mekaniks ng laro:"
        1. May walong (8) misyon na dapat kompletuhin ng manlalaro.
        2. Ang bawat misyon ay kinakailangan matapos base sa pagkasunod-sunod para makausad sa susunod na misyon.
        3. Bago makapagmaneho ay kinakailangan munang masuri ang sasakyan. 
        4. Kailangang masuri ng manlalaro ang BLOWBAGETS.
        5. Kailangang mag-seatbelt ang manlalaro bago magsimula sa kanyang misyon.
        6. Kailangang makontrol ng maayos ang mga kontrol para matapos ang mga misyon.
        7. Isa lang ang buhay sa bawat misyon.
        8. Upang mapanatili ang buhay ay kinakailangang iwasan ang mga tumatawid at ang ibang nakaparadang sasakyan.
        9. Matapos kompletuhin ang mga misyon ay kusang malilipat ang manlalaro sa susunod na misyon.
        10.Matapos ang mga misyon, magpapakita ng anunsyo ang laro na matagumpay na natapos ang Stepped Application.

    "<b>MGA KONTROLS AT TAGAPAGPAHIWATIG"
        Speedometer - nagsasaad ng bilis ng sasakyan.
        Mga Senyales – senyas sa pagliko para sa ligtas na pagmamaneho at pagpaparada.
    	Manibela – nagbibigay ng kontrol sa direksyon ng sasakyan
        Susi - sinisimulan at ihihinto ang makina. Makakapag-maneho o maititigil ang sasakyan kapag pinindot ang susi.
        Handbrake - preno na ginagamitan ng kamay upang pansamantalang ihinto ang sasakyan.
        Primera – unang gear sa bilis ng pagpapatakbo ng sasakyan.
        Segunda - tinataas ang bilis mula sa unang gear. 
        Trisera - tinataas ang bilis mula sa pangalawang gear. 
        Kwarta - tinataas ang bilis mula sa pangatlong gear. 
        Quinta – huling gear at pinapataas ang bilis ng sasakyan.
        Paatras na Buton - pinapaatras ang sasakyan.
        Neutral na Buton - pinipigilan ang galaw ng sasakyan.
        Kambyo na Pedal - nagpapahintulot sa driver na maayos na ilipat ang mga gears.
        Preno - pansamantalang itinitigil ang sasakyan.
        Akselerador - nagmamaneho pasulong at paatras ng sasakyan.